### ISSUE TITLE
Excuse me, please tell me, what's the different between your two project

### ISSUE THREAD

**Issue by wildfire810** [jonschlinkert/normalize-path#10] opened 2018-11-11 08:03 UTC
Excuse me, please tell me, what's the different between your two project
https://github.com/jonschlinkert/unixify
https://github.com/jonschlinkert/normalize-path
Thanks :)

**Comment by doowb** [comment] 2018-11-11 16:58
Duplicate of https://github.com/jonschlinkert/unixify/issues/1

**Closed as completed by doowb** 2018-11-11 16:58 UTC
